trigger:
  - master
  
pool:
  # vmImage: 'ubuntu-latest'
  name: Default
  demands: 
    - HOME_NETWORK
    #  - agent.os -equals Darwin  # check for specific string in capability


variables: 
- group: Secrets
- name: stack
  value: $(Build.SourceBranchName)

steps:
- script: docker login --username alexbechmann --password $(DOCKER_TOKEN)
  displayName: Docker login

- script: |
    STACK=$(echo "$(system.pullRequest.sourceBranch)" | iconv -t ascii//TRANSLIT | sed -r s/[~\^]+//g | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-)
    echo "stack is $STACK"
    echo "##vso[task.setvariable variable=stack]$STACK"

- script: pulumi stack init $(stack)
  workingDirectory: pulumi

- script: npm --prefix $(System.DefaultWorkingDirectory)/pulumi install
  displayName: 'Pulumi web npm install'
  
- script: pulumi preview --stack $(stack) --cwd $(System.DefaultWorkingDirectory)/pulumi
  displayName: 'Preview Pulumi'

# - script: |
#     /home/vsts/.pulumi/bin/pulumi up --stack $(Build.SourceBranchName) --yes --cwd $(System.DefaultWorkingDirectory)/pulumi/web
#   displayName: 'Deploy with Pulumi'
#   condition: and(succeeded(), in(variables['Build.SourceBranchName'], 'master', 'develop'))
