trigger:
  - master
  
pool:
  # vmImage: 'ubuntu-latest'
  demands: 
    - HOME_NETWORK
    #  - agent.os -equals Darwin  # check for specific string in capability


variables: 
  group: Secrets

steps:
- script: | 
    curl -fsSL https://get.pulumi.com | sh
  displayName: Install Pulumi

- script: docker login --username alexbechmann --password $(DOCKER_TOKEN)
  displayName: Docker login

- script: pulumi stack init staging
  continueOnError: true

- script: npm --prefix $(System.DefaultWorkingDirectory)/pulumi/web install
  displayName: 'Pulumi web npm install'
  
# - script: /home/vsts/.pulumi/bin/pulumi preview --stack develop --cwd $(System.DefaultWorkingDirectory)/pulumi/web
#   displayName: 'Preview Pulumi'

# - script: |
#     /home/vsts/.pulumi/bin/pulumi up --stack $(Build.SourceBranchName) --yes --cwd $(System.DefaultWorkingDirectory)/pulumi/web
#   displayName: 'Deploy with Pulumi'
#   condition: and(succeeded(), in(variables['Build.SourceBranchName'], 'master', 'develop'))
