trigger:
  - master
  
pool:
  # vmImage: 'ubuntu-latest'
  name: Default
  demands: 
    - HOME_NETWORK
    #  - agent.os -equals Darwin  # check for specific string in capability


variables: 
  group: Secrets

steps:
- script: docker login --username alexbechmann --password $(DOCKER_TOKEN)
  displayName: Docker login

- script: |
    SLUG=$(echo "$(system.pullRequest.sourceBranch)" | iconv -t ascii//TRANSLIT | sed -r s/[~\^]+//g | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-)
    echo "slug is $SLUG"
    
- script: 
    SLUG=$(Build.SourceBranchName)
  condition: in(variables['Build.SourceBranchName'], 'master', 'develop', 'release')


# - script: pulumi stack init staging
#   workingDirectory: pulumi
#   continueOnError: true

- script: npm --prefix $(System.DefaultWorkingDirectory)/pulumi install
  displayName: 'Pulumi web npm install'
  
# - script: /home/vsts/.pulumi/bin/pulumi preview --stack develop --cwd $(System.DefaultWorkingDirectory)/pulumi/web
#   displayName: 'Preview Pulumi'

# - script: |
#     /home/vsts/.pulumi/bin/pulumi up --stack $(Build.SourceBranchName) --yes --cwd $(System.DefaultWorkingDirectory)/pulumi/web
#   displayName: 'Deploy with Pulumi'
#   condition: and(succeeded(), in(variables['Build.SourceBranchName'], 'master', 'develop'))
