apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "dotdev-{{ .Values.env }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: dotdev-{{ .Values.env }}.alexbechmann.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
    - host: alexbechmann.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
  tls:
    - hosts:
        - dotdev-{{ .Values.env }}.alexbechmann.dev
      secretName: dotdev-{{ .Values.env }}.alexbechmann.dev
    - hosts:
        - alexbechmann.dev
      secretName: alexbechmann.dev
